djangoapp/Carbono/urls.py
from django.urls import path 
from . import views 
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.home, name = 'home'),
    path('login/', views.login_view, name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('imovel/<int:imovel_id>_<slug:imovel_nome>/', views.imovel_detalhes, name = 'imovel_detail'),
    path('grafico/', views.graficos, name='graficos'),
    path('api/views_data/', views.get_views_data, name='get_views_data'),
    path('quem-somos/', views.quem_somos, name='_quem_somos'),
    path('fale-conosco/', views.termos_condicoes, name='_fale_conosco'),
    path('termos-condicoes/', views.termos_condicoes, name='_termos_condicoes'),
    path('imovel/pesquisa/', views.imovel_pesquisa, name = 'imovel_pesquisa'),
]

djangoapp/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Carbono.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

djangoapp/Carbono/models.py
from django.db import models
from django.utils import timezone
import re
import os

# Create your models here.

class TipoImovel(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Tipo de Imóvel'
        verbose_name_plural = 'Tipos de Imóveis'
        ordering = ['nome']

class Imovel(models.Model):
    titulo = models.CharField(verbose_name="Título do Imóvel",max_length=200)
    tipo_imovel = models.ForeignKey(TipoImovel,verbose_name="Tipo do Imóvel", on_delete=models.CASCADE)
    descricao = models.TextField(verbose_name="Descrição")
    preco = models.DecimalField(verbose_name="Preço do Imóvel",max_digits=15, decimal_places=2)
    endereco = models.CharField(verbose_name="Endereço",max_length=200)
    cidade = models.CharField(verbose_name="Cidade",max_length=100)
    qtd_quartos = models.IntegerField(verbose_name="Qtd Quartos")
    qtd_banheiros = models.IntegerField(verbose_name="Qtd Banheiros")
    qtd_comodos = models.IntegerField(verbose_name="Qtd Comodos Totais")
    data_geracao = models.DateTimeField(default=timezone.now, editable=False)
    destaque = models.BooleanField(default=False)
    visualizacoes = models.PositiveIntegerField(default=0,editable=False)

    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name = 'Imóvel'
        verbose_name_plural = 'Imóveis'
        ordering = ['titulo']

def upload_to(instance,filename): 
    base_filename, extension = os.path.splitext(filename)
    title = instance.imovel.titulo
    # Remove caracteres especiais e espaços
    clean_title = re.sub(r'[^\w\s-]', '', title).strip()
    # Substitui espaços por underscores
    clean_title = re.sub(r'\s+', '_', clean_title)
    # Limita o tamanho do título para evitar nomes de arquivo muito longos
    max_length = 30  
    final_title = clean_title[:max_length]
    return f"imoveis/{final_title}-{instance.imovel.id}{extension}"
    
class FotosDosImoveis(models.Model):
    imovel = models.ForeignKey(Imovel, on_delete=models.CASCADE)
    foto =  models.ImageField(upload_to=upload_to)

    def __str__(self):
        return f"Foto do imóvel: {self.imovel.titulo}"

    class Meta:
        verbose_name = 'Foto do Imóvel'
        verbose_name_plural = 'Fotos dos Imóveis'
        
 
class RedesSociaisManager(models.Manager):
    def get_singleton(self):
        obj, created = self.get_or_create(pk=1)
        return obj       
        
class RedesSociais(models.Model):
    facebook = models.CharField(verbose_name='Facebook',max_length=300,help_text='Insira o link para a página do Facebook.')
    instagram = models.CharField(verbose_name='Instagram',max_length=300,help_text='Insira o link para a página do Instagram.')
    whatsapp = models.CharField(verbose_name='WhatsApp',max_length=300,help_text='Insira o link para a contado do Whatsapp.')
    
    
    def save(self, *args, **kwargs):
        if not self.pk and RedesSociais.objects.exists():
            return  # Apenas uma instância permitida
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Rede Social'
        verbose_name_plural = 'Redes Socias'
        
    
    def __str__(self):
        return "Configurações de Redes Sociais"
    
class Textosdofooter(models.Model):
    quem_somos = models.TextField(verbose_name="Texto 'Quem Somos'",help_text="Insira o texto para ser exibido ao clicar em 'Quem Somos.'")
    fale_conosco = models.TextField(verbose_name="Texto 'Fale Conosco'",help_text="Insira o texto para ser exibido ao clicar em 'Fale Conosco.'")
    termos_condicoes = models.TextField(verbose_name="Texto 'Termos e Condições'",help_text="Insira o texto para ser exibido ao clicar em 'termos e Condições.'")
   
    def save(self, *args, **kwargs):
        if not self.pk and Textosdofooter.objects.exists():
            return  # Apenas uma instância permitida
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Texto do roda-pé'
        verbose_name_plural = 'Textos do roda-pé'
        
    def __str__(self):
        return "Configurações de Textos do rada-pé" 

djangoapp/Carbono/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login ,logout
from .models import Imovel,TipoImovel,RedesSociais,Textosdofooter
from django.http import JsonResponse


# Create your views here.
def home(request):
    imoveis = Imovel.objects.filter(destaque=True)
    redessociais = RedesSociais.objects.all()
    tipoimoveis = TipoImovel.objects.all()
    mensagem = Textosdofooter.objects.all()
    
    search_query = request.GET.get('search')
    tipo_id = request.GET.get('tipo')
    
    filtro_tipoimovel = False
    filtro_tituloimovel = False
    tipo_imovel_psq = search_query
    
    if tipo_id:
        tipo_imovel = TipoImovel.objects.get(pk=tipo_id)
        tipo_imovel_nome = tipo_imovel.nome
        imoveis = imoveis.filter(tipo_imovel=tipo_imovel)
        filtro_tipoimovel = True
        tipo_imovel_psq = search_query
        
    else:
        tipo_imovel_nome = None
    
    if search_query:
        imoveis = Imovel.objects.filter(titulo__icontains = search_query)
        tipo_imovel_psq = search_query
        filtro_tituloimovel = True
        
    context = {'imoveis': imoveis, 
               'tipoimoveis':tipoimoveis,
               'redessociais':redessociais,
               'tipo_imovel_nome':tipo_imovel_nome,
               'tipo_imovel_psq':tipo_imovel_psq,
               'filtro_tipoimovel':filtro_tipoimovel,
               'filtro_tituloimovel':filtro_tituloimovel,
               'mensagems':mensagem,}
    
    if not imoveis:
        context['empty_message'] = "Nenhum imóvel encontrado para essa seleção."
        
    return render(request, 'home.html',context)

def quem_somos(request):
    mensagem = Textosdofooter.objects.all()
    return render(request, '_quem_somos.html', {'mensagems': mensagem})

def fale_conosco(request):
    mensagem = Textosdofooter.objects.all()
    return render(request, '_fale_conosco.html', {'mensagems': mensagem})

def  termos_condicoes(request):
    mensagem = Textosdofooter.objects.all()
    return render(request, '_termos_condicoes.html', {'mensagems': mensagem})

def imovel_pesquisa(request):
    return render(request, 'imoveis/pesquisa_imoveis.html')

@login_required
def graficos(request):
    imoveis = Imovel.objects.all() 
    context = {'imoveis': imoveis}
    return render(request, 'graficos.html', context)

def imovel_detalhes(request, imovel_id, imovel_nome):
    imovel = get_object_or_404(Imovel, pk=imovel_id)
    imovel.visualizacoes += 1
    imovel.save()

    context = {'imovel': imovel}
    return render(request, 'imoveis/detalhe_imovel.html', context)
    pass

def get_views_data(request):
    imoveis = Imovel.objects.all()
    data = {
        'labels': [imovel.titulo for imovel in imoveis],
        'data': [imovel.visualizacoes for imovel in imoveis],
    }
    return JsonResponse(data)

def login_view(request):
    if request.method == 'POST':
        usuario = request.POST['usuario']
        senha = request.POST['senha']
        user = authenticate(request, username=usuario, password=senha)


        if not usuario:
            senha_incorreta = False
            usuario_vazia = True
            return render(request, 'cadastros/login.html',{'usuario_vazia': True})
                
        elif not senha:
            senha_incorreta = False
            senha_vazia = True
            return render(request, 'cadastros/login.html',{'senha_vazia': True})

        if user is not None:
            login(request, user)
            senha_incorreta = False
            return redirect('/admin/')

        else:
            senha_incorreta = True
            return render(request, 'cadastros/login.html', {'senha_incorreta': True})
            
    return render(request, 'cadastros/login.html')

def LogoutView(request):
    logout(request)
    return redirect('/admin/')
        

djangoapp/Carbono/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'img/carbono-icon.png'%}" type="image/x-icon">
    {%block 'liks'%}{%endblock%}
    <title>{%block 'titulo'%}{%endblock%} | Corretora Carbono</title>
</head>
    {%block 'conteudo'%}
    {%endblock%}

djangoapp/Carbono/templates/graficos.html
{% extends 'base.html' %}
{% block 'titulo' %}Graficos{% endblock %}
{% load static %} 
{%block 'liks' %}<link rel="stylesheet" type="text/css" href="{% static 'style\visual-graficos.css' %}."/>{%endblock%}

{% block 'conteudo' %}
    <h1>Gráfico de Visualizações</h1>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <!-- Seu conteúdo HTML aqui -->

  <div class="chart-container">
    <canvas id="views-chart"></canvas>
  </div>
  <script type="text/javascript" src="{% static 'js/graficos.js' %}"></script>
{% endblock %}

djangoapp/Carbono/templates/home.html
{%extends 'base.html'%} 
{%block 'titulo'%}HomePage{%endblock %} 
{%block 'conteudo'%} 
{% load static %} 
{%block 'liks' %}<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'style\visual-home.css' %}"/>{%endblock%}
<body>
  <header>
    <div>
        <a href="{% url 'home'%}"  style="display: inline-block; margin: 0; padding: 0;">
          <img class="img-logo" src="{% static 'img/carbono-icon.png'%}" alt="img logo Carbono" width="50">
        </a>
        <form method="GET" action="">
            <input class="busca-texto" type="text" name="search" placeholder="Pesquisar...">
            <button type="submit">Buscar</button>
        </form>
    </div>
    {% if user.is_authenticated %}
      <a class="cabecalho-nav-link-usuario" href="{% url 'admin:index'%}">{{request.user}}</a>
      <a class="cabecalho-nav-link-usuario" href="{% url 'graficos'%}">Ver Graficos</a>
      <a class="cabecalho-nav-link-usuario" href="{% url 'logout'%}">Sair</a>
    {% else %}
      <a class="cabecalho-nav-link-usuario" href="{% url 'login'%}">Login</a>
    {% endif %}
  </header>
  <main class="container-categoria">
    <div class="categoria">
        <h2>Tipos de imoveis</h2>
        <section class="categoria-section">
            <ul>
              {% for tipoimovel in tipoimoveis%}
                <li><a class="nav-categorias-link" href="?tipo={{tipoimovel.id}}">{{tipoimovel.nome}}</a></li>
              {% endfor %}
            </ul>
        </section>
    </div>
  </main>
    {% if filtro_tituloimovel or filtro_tipoimovel %}
      {% if tipo_imovel_nome%}
        <h2 class=" destaques-titulo">Filtrando pelo tipo imóvel: {{ tipo_imovel_nome }}</h2>
      {% elif tipo_imovel_psq %}
        <h2 class=" destaques-titulo">Filtrando pelo titulo: {{tipo_imovel_psq}}</h2>  
      {% endif%}
    {% else%}
      <h2 class=" destaques-titulo">Destaques</h2>
    {% endif %}
    <section class="container-destaques">
      {% if imoveis%}
        {% for imovel in imoveis %}
          <div class="destaques-item">
              <a class="item-link" href="{% url 'imovel_detail' imovel_id=imovel.id imovel_nome=imovel.titulo|slugify %}">
                  {% if imovel.fotosdosimoveis_set.first.foto.url %}
                    <img src="{{ imovel.fotosdosimoveis_set.first.foto.url }}" alt="imagem de {{imovel.titulo}}"/>
                  {% else %}
                    <img  src="{% static 'media/imoveis/default.png' %}" alt="imagem de {{imovel.titulo}}"/>
                  {% endif %}
                  <h2><a class="btn btn-dark" href="{% url 'imovel_detail' imovel_id=imovel.id imovel_nome=imovel.titulo|slugify %}">{{imovel.titulo}}</a></h2>
                  <p class="item-valor">R$ {{ imovel.preco }}</p>
                  <p class="item-data">Publicado em {{imovel.data_geracao}}</p>
                  <div>
                    <span class="span-categoria">{{imovel.tipo_imovel.nome}}</span>
                  </div>
              </a>
          </div>
        {% endfor %}
      {% else%}
        <p style="color: red">Nenhum imóvel encontrado para essa seleção.</p>
      {% endif%}
      {% include 'footer/_quem_somos.html'  %}
      {% include 'footer/_fale_conosco.html'  %}
      {% include 'footer/_termos_condicoes.html' %}
    </section>
    <footer>
      <div class="footer-redes">
        <h3>Redes Sociais</h3>
        {% for redessocial in redessociais%}
          <a href="{{redessocial.instagram}}" target="_blank">Instagram</a>
          <a href="{{redessocial.facebook}}" target="_blank">Facebook</a>
          <a href="{{redessocial.whatsapp}}" target="_blank">Whatsapp</a>
        {% endfor %}
      </div>
    <div class="footer-redes">
        <h3>Menu</h3>
        <a href="{% url '_quem_somos' %}" class="link-mensagem-quem-somos">Quem Somos</a>
        <a href="{% url '_fale_conosco'%}" class="link-mensagem-fale-conosco" >Fale Conosco</a>
        <a href="{% url '_termos_condicoes'%}" class="link-mensagem-termos-condicoes">Termos e Condições</a>
    </div>
    </footer>
  <script>
    document.querySelectorAll('.link-mensagem-termos-condicoes').forEach(function(link) {
        link.addEventListener('click', function(event) {
            event.preventDefault();
            var mensagemElement = document.querySelector('.mensagem-termos-condicoes');
            if (mensagemElement) {
                mensagemElement.style.display = mensagemElement.style.display === 'block' ? 'none' : 'block';
            }
        });
    });
  </script>
  <script>
    document.querySelectorAll('.link-mensagem-quem-somos').forEach(function(link) {
        link.addEventListener('click', function(event) {
            event.preventDefault();
            var mensagemElement = document.querySelector('.mensagem-quem-somos');
            if (mensagemElement) {
                mensagemElement.style.display = mensagemElement.style.display === 'block' ? 'none' : 'block';
            }
        });
    });
</script>
<script>
  document.querySelectorAll('.link-mensagem-fale-conosco').forEach(function(link) {
      link.addEventListener('click', function(event) {
          event.preventDefault();
          var mensagemElement = document.querySelector('.mensagem-fale-conosco');
          if (mensagemElement) {
              mensagemElement.style.display = mensagemElement.style.display === 'block' ? 'none' : 'block';
          }
      });
  });
</script>
</body>
{%endblock%}